### ISSUE TITLE
Train a ML model to detect toddlers

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#17]
Find proper data and training for toddler detection from a camera in the corner of the room perspective.

**Comment by Abdumbo99** [comment]
Add sub-tasks as you see necessary

**Comment by esattok** [comment]
<img width="705" alt="faster_r_cnn" src="https://user-images.githubusercontent.com/86562400/235368683-aea2b295-558b-4d8a-979c-f0b16100ff0e.png">

**Comment by esattok** [comment]
Below are the evaluation outputs of several model architectures that we trained as candidates of the application. 

The meaning of the evaluation (in summary): 

- The model includes the object detections of all the objects (baby, pen, knife, scissor, door, window). So the evaluation matrix does not show the precisions class by class. 
- The first row is the precision of the model in total and the main metric that we desire to be good.
- Average Precision rows are the ones that are relevant to us not the Average Recall ones
- As we realized by our researches, detecting  small objects are a general problem of object detection. Since the model architectures are cropping the images into pieces, small images are lost for the models that do not deeply sophisticated. Therefore being able to detect small images requires more performance.
- Also another problem of models is the difficulty of detecting small objects as well as large objects in the same image since the crops are at the same rates.
- The models that can better detect small objects as well as large objects are the ones that require more calculation power and not suitable for embedded devices.
- Therefore we are required to make trade offs and to choose the best architecture possible considering the speed, accuracy, and computational power requirements.

Below are the models and their corresponding information to consider (many more models have been trained and tested but only the possible candidates in terms of average precision and compatibility are listed):

The evaluation below belongs to the architecture `faster r-cnn`. 

- It is one of the best possible architectures and gives one of the best average precisions.
- But it cannot be converted to `.tflite` format.
- Therefore if we want to use that model we need to change the structure of the application to use the saved model rather than the .tflite file which is not feasible.

<img width="705" alt="faster_r_cnn" src="https://user-images.githubusercontent.com/86562400/235368713-811f333a-c625-4128-a5a6-f02ce0dffb39.png">

The evaluation below belongs to the architecture `efficientdet_d1_640x640`.

- the average precision of this model is low.
- it can be converted to `.tflite` format.
- speed (ms): 54, COCO mAP (means basically the mean average precision on the COCO dataset that the model is created): 38.4

<img width="677" alt="efficientdet_d1" src="https://user-images.githubusercontent.com/86562400/235369623-218b8bb7-7178-40ee-b07a-235aeac2ddc9.png">

The evaluation below belongs to the architecture `efficientdet_d4_1024x1024`.

- the average precision of this model is higher than the 640x640 version of the same architecture considering its speed, it is not desirable.
- it can be converted to `.tflite` format.
- speed (ms): 133, COCO mAP (means basically the mean average precision on the COCO dataset that the model is created): 48.5
- even though COCO mAP of the model is higher efficientdet models are not good and preferred on detection of small objects.

<img width="698" alt="efficientdet_d4" src="https://user-images.githubusercontent.com/86562400/235369799-9f8da3ff-23c0-4886-b498-189995b8a5ea.png">

The evaluation below belongs to the architecture `centernet_resnet_101_V1_FPN_512x512`.

- the average precision of this model is high compared to its speed.
- it can be converted to `.tflite` format.
- speed (ms): 34, COCO mAP (means basically the mean average precision on the COCO dataset that the model is created): 34.2
- the architectures that use FPN like this model, has a relatively good performance on detecting small objects.
- In the centernet models the mAP (mean average precision) is high considering its speed so it may be better for PI.

<img width="694" alt="centernet_resnet_101" src="https://user-images.githubusercontent.com/86562400/235369981-2348e785-56bd-417a-991c-56b90859f22e.png">

The evaluation below belongs to the architecture `centernet_HOURGLASS104_512x512`.

- the average precision of this model is high pretty high.
- it can be converted to `.tflite` format.
- speed (ms): 70, COCO mAP (means basically the mean average precision on the COCO dataset that the model is created): 41.9
- this model is a good candidate but it does not uses fixed_shape_resizer as preprocessing.
- because of the above item this model cannot be converted to .tflite.

<img width="710" alt="centernet_hourglass_512" src="https://user-images.githubusercontent.com/86562400/235370121-3350ff91-4276-4685-99de-c4c98d43c2b6.png">

The evaluation below belongs to the architecture of modified version of  `centernet_HOURGLASS104_512x512`.

- it is the same model as above but the pipeline.config file is modified so that the model now uses fixed_shape_resizer to be converted to .tflite format
- it can be converted to `.tflite` format.
- this model is the best candidate to use in our application since its speed is considerably low compared to the other models that do not have as good precision evaluation matrix as this one

<img width="679" alt="centernet_hourglass_512_fixed_size" src="https://user-images.githubusercontent.com/86562400/235370212-75c08e75-dad2-40b1-8c4b-073dbf5db7dc.png">

Therefore in summary modified version of  `centernet_HOURGLASS104_512x512` is the best model so far that can be used.

**Comment by esattok** [comment]
- Below is the images of the detected object captured with cv2. 
- Since performed on google colab, the precision labels are small but the images are captured by cv2 so that only the objects that are detected above 0.5 precision are labeled so the images below are all > 0.5 in terms of precision (this corner case is valid for small objects (pen, knife, scissor)). 
- The precision of the large images (baby, door, window) are detected with > 0.8 precision.

<img width="452" alt="Screenshot 2023-04-30 at 11 07 20" src="https://user-images.githubusercontent.com/86562400/235370390-41348c9f-633e-45f3-9940-35b054db24fb.png">

<img width="458" alt="Screenshot 2023-04-30 at 12 53 25" src="https://user-images.githubusercontent.com/86562400/235370400-680e3c22-2c0b-4aa5-8714-783534dcdcc2.png">

The relevant issues are closed that are done.

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="177" alt="Screen Shot 2023-05-07 at 01 08 21" src="https://user-images.githubusercontent.com/86562400/236672424-322e1b64-6356-425f-9e6e-8b47fc0d51df.png">
<img width="172" alt="Screen Shot 2023-05-07 at 01 08 04" src="https://user-images.githubusercontent.com/86562400/236672426-86502d50-f0e5-41d8-a364-315b53c5dbe2.png">
<img width="183" alt="Screen Shot 2023-05-07 at 01 07 53" src="https://user-images.githubusercontent.com/86562400/236672430-24c09bc0-3306-4d01-86a7-0ab8161d8257.png">
<img width="399" alt="Screen Shot 2023-05-06 at 23 53 53" src="https://user-images.githubusercontent.com/86562400/236672436-48ea35ec-79cc-43f8-8565-58a6e0853dc2.png">
<img width="274" alt="Screen Shot 2023-05-06 at 23 52 15" src="https://user-images.githubusercontent.com/86562400/236672447-0128d32d-f6e5-483c-9ab0-22109d5fa455.png">
